In [1]:
import os
import pandas as pd
from google.cloud import bigquery
from google.oauth2.service_account import Credentials
import db_dtypes

In [2]:
# BIGQUERY_CREDENTIALS_FILE_PATH = r"C:\TIR101_Group2\secrets\harry_GCS_BigQuery_write_cred.json"
BIGQUERY_CREDENTIALS_FILE_PATH = r"D:\data_engineer\TIR_group2\TIR101_Group2\secrets\harry_GCS_BigQuery_write_cred.json"
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = BIGQUERY_CREDENTIALS_FILE_PATH

In [3]:
BQ_CLIENT = bigquery.Client()

In [10]:
BQ_CLIENT.project

'tir101-group2-422603'

In [ ]:
def create_dataset(dataset_name:str , location:str="asia-east1",client: bigquery.Client = BQ_CLIENT):
    porject_name = client.project
    dataset_id = f"{porject_name}.{dataset_name}"

    dataset = bigquery.Dataset(dataset_id)
    dataset.location = location

    client.create_dataset(dataset)
    print(f"created {dataset_name} in project {porject_name} ,location:{location}")
create_dataset(dataset_name="Youbike_ODS")

In [33]:
def youbike_gcs_src_to_bq(client: bigquery.Client = BQ_CLIENT) -> None:
    query_job = client.query(
    """
        CREATE OR REPLACE EXTERNAL TABLE `Youbike_ODS.youbike_src`
        WITH PARTITION COLUMNS
        OPTIONS (
        format = 'CSV',
        uris = ['gs://youbike_realtime/*.csv'],
        hive_partition_uri_prefix = 'gs://youbike_realtime/',
        skip_leading_rows = 1,
        max_bad_records = 1
        );
    """
    )

    query_job.result()
    print("youbike_gcs_src_to_bq updated.")
youbike_gcs_src_to_bq()

youbike_gcs_src_to_bq updated.

In [49]:
def youbike_gcs_src_to_bq_before0504(client: bigquery.Client = BQ_CLIENT) -> None:
    query_job = client.query(
    """
        CREATE OR REPLACE EXTERNAL TABLE `Youbike_ODS.youbike_src_before_0504`
        (
            sno INT,
            sna STRING,
            tot INT,
            sbi INT,
            sarea STRING,
            mday TIMESTAMP,
            lat FLOAT64,
            lng FLOAT64,
            ar STRING,
            sareaen STRING,
            snaen STRING,
            aren STRING,
            bemp INT,
            act INT,
            srcUpdateTime TIMESTAMP,
            updateTime TIMESTAMP,
            infoTime TIMESTAMP,
            infoDate DATE
        )
        WITH PARTITION COLUMNS
        OPTIONS (
            format = 'CSV',
            uris = ['gs://youbike_realtime/v1_data/*.csv'],
            hive_partition_uri_prefix = 'gs://youbike_realtime/v1_data/',
            skip_leading_rows = 1,
            max_bad_records = 1
        );
    """
    )

    query_job.result()
    print("youbike_gcs_src_to_bq_before0504 updated.")
youbike_gcs_src_to_bq_before0504()

youbike_gcs_src_to_bq_before0504 updated.

In [38]:
def youbike_gcs_src_to_bq(client: bigquery.Client = BQ_CLIENT) -> None:
    query_job = client.query(
    """
        CREATE OR REPLACE EXTERNAL TABLE `Youbike_ODS.youbike_src`
        (
            sno INT,
            sna  STRING,
            sarea STRING,
            mday TIMESTAMP,
            ar STRING,
            sareaen STRING,
            snaen  STRING,
            aren STRING,
            act INT,
            srcUpdateTime TIMESTAMP,
            updateTime TIMESTAMP,
            infoTime TIMESTAMP,
            infoDate DATE,
            total INT,
            available_rent_bikes INT,
            latitude FLOAT64,
            longitude FLOAT64,
            available_return_bikes INT
        )
        WITH PARTITION COLUMNS
        OPTIONS (
            format = 'CSV',
            uris = ['gs://youbike_realtime/v2_data/*.csv'],
            hive_partition_uri_prefix = 'gs://youbike_realtime/v2_data/',
            skip_leading_rows = 1,
            max_bad_records = 1
        );
    """
    )

    query_job.result()
    print("youbike_gcs_src_to_bq updated.")
youbike_gcs_src_to_bq()

youbike_gcs_src_to_bq updated.

In [ ]:
def youbike_gcs_src_to_bq(client: bigquery.Client = BQ_CLIENT) -> None:
    query_job = client.query(
    """
        CREATE OR REPLACE EXTERNAL TABLE `Youbike_ODS.youbike_src`
        (
            sno INT,
            sna  STRING,
            sarea STRING,
            mday TIMESTAMP,
            ar STRING,
            sareaen STRING,
            snaen  STRING,
            aren STRING,
            act INT,
            srcUpdateTime TIMESTAMP,
            updateTime TIMESTAMP,
            infoTime TIMESTAMP,
            infoDate DATE,
            total INT,
            available_rent_bikes INT,
            latitude FLOAT64,
            longitude FLOAT64,
            available_return_bikes INT
        )
        WITH PARTITION COLUMNS
        OPTIONS (
            format = 'CSV',
            uris = ['gs://youbike_realtime/v2_data/*.csv'],
            hive_partition_uri_prefix = 'gs://youbike_realtime/v2_data/',
            skip_leading_rows = 1,
            max_bad_records = 1
        );
    """
    )

    query_job.result()
    print("youbike_gcs_src_to_bq updated.")
youbike_gcs_src_to_bq()

youbike_gcs_src_to_bq updated.

In [ ]:
# # ALTER TABLE mydataset.mytable
# #   RENAME COLUMN old_name TO new_name;
# CREATE TABLE `bike_station` (
#   `bike_station_id` int PRIMARY KEY,
#   `station_name` varchar(100),
#   `total_space` int,
#   `lat` decimal(8,6),
#   `lng` decimal(9,6),
#   `city_code` char(3),
#   `district` varchar(20),
#   `address` varchar(100),
#   `disable` boolean,
#   `create_time` timestamp default current_timestamp,
#   `update_time` timestamp default current_timestamp
# );

# CREATE TABLE `bike_latest_update` (
#   `bike_station_id` int PRIMARY KEY,
#   `aval_bike` int,
#   `aval_space` int,
#   `source_time` timestamp,
#   `create_time` timestamp default current_timestamp
# );

# CREATE TABLE `bike_realtime` (
#   `bike_station_id` int,
#   `aval_bike` int,
#   `aval_space` int,
#   `source_time` timestamp,
#   `create_time` timestamp default current_timestamp,
#   PRIMARY KEY (`bike_station_id`, `create_time`)
# );

In [ ]:
# def youbike_src_rename(client: bigquery.Client = BQ_CLIENT):
#     query_job = client.query(
#     """
#         ALTER TABLE `Youbike_ODS.youbike_src`
#             RENAME COLUMN `sno` TO `bike_station_id`,
#             RENAME COLUMN `sna` TO `station_name`,
#             RENAME COLUMN `sarea` TO `district`,
#             RENAME COLUMN `mday` TO `make_date`,
#             RENAME COLUMN `ar` TO `address`,
#             RENAME COLUMN `sareaen` TO `district_eng`,
#             RENAME COLUMN `snaen`  TO `station_name_eng`,
#             RENAME COLUMN `aren` TO `address_eng`,
#             RENAME COLUMN `act` TO `disable`,
#             RENAME COLUMN `srcUpdateTime` TO `source_time`,
#             RENAME COLUMN `updateTime` TO `update_time`,
#             #RENAME COLUMN `infoTime` TO `info_Time`,
#             #RENAME COLUMN `infoDate` TO `info_Date`,
#             RENAME COLUMN `total` TO `total_space`,
#             RENAME COLUMN `available_rent_bikes` TO `aval_space`,
#             RENAME COLUMN `latitude` TO `lat`,
#             RENAME COLUMN `longitude` TO `lng`,
#             RENAME COLUMN `available_return_bikes` TO `aval_return`;
#     """
#     )
#     query_job.result()
#     print(f"Youbike_ODS.youbike_src has been renamed")

# youbike_src_rename()

In [74]:
def youbike_ods_create(client: bigquery.Client = BQ_CLIENT):
    query_job = client.query(
    """
    CREATE OR REPLACE TABLE `Youbike_ODS.youbike_ods` AS
    SELECT
        sno AS bike_station_id,
        sna AS station_name,
        sarea AS district,
        mday AS make_date,
        ar AS address,
        sareaen AS district_eng,
        snaen AS station_name_eng,
        aren AS address_eng,
        act AS disable,
        srcUpdateTime AS source_time,
        updateTime AS create_time,
        infoTime,
        infoDate,
        total AS total_space,
        available_rent_bikes AS aval_bike,
        latitude AS lat,
        longitude AS lng,
        available_return_bikes AS aval_space
    FROM `Youbike_ODS.youbike_src`;
    """
    )
    query_job.result()
    print(f"Youbike_ODS.youbike_ods has been created")

youbike_ods_create()

Youbike_ODS.youbike_ods has been created

In [75]:
def youbike_ods_before0504_create(client: bigquery.Client = BQ_CLIENT):
    query_job = client.query(
    """
    CREATE OR REPLACE TABLE `Youbike_ODS.youbike_ods_before0504` AS
    SELECT
        sno AS bike_station_id,
        sna AS station_name,
        sarea AS district,
        mday AS make_date,
        ar AS address,
        sareaen AS district_eng,
        snaen AS station_name_eng,
        aren AS address_eng,
        act AS disable,
        srcUpdateTime AS source_time,
        updateTime AS create_time,
        infoTime,
        infoDate,
        tot AS total_space,
        sbi AS aval_bike,
        lat,
        lng,
        bemp AS aval_space
    FROM `Youbike_ODS.youbike_src_before_0504`;
    """
    )
    query_job.result()
    print(f"Youbike_ODS.youbike_ods_before0504 has been created")

youbike_ods_before0504_create()

Youbike_ODS.youbike_ods_before0504 has been created

In [76]:
def youbike_ods_combine_create(client: bigquery.Client = BQ_CLIENT):
    query_job = client.query(
    """
    CREATE OR REPLACE TABLE `Youbike_ODS.youbike_ods_rename` AS
        (   SELECT * 
                FROM `Youbike_ODS.youbike_ods_before0504`
            UNION ALL
            SELECT * 
                FROM `Youbike_ODS.youbike_ods`
        )
        ;
    """
    )
    query_job.result()
    print(f"Youbike_ODS.youbike_ods_rename has been created")

youbike_ods_combine_create()

Youbike_ODS.youbike_ods_rename has been created

In [ ]:
def youbike_ods_(client: bigquery.Client = BQ_CLIENT):
    query_job = client.query(
    """
    CREATE OR REPLACE TABLE `Youbike_ODS.bike_station` AS
    SELECT 
        `bike_station_id`,
        `station_name`,
        `total_space`,
        `lat`,
        `lng`,
        `district` ,
        `address`,
        `disable`,
        `create_time`,
        `update_time` 
    FROM `Youbike_ODS.youbike_ods_rename`
    GROUP BY `bike_station_id`
    HAVING `create_time` = MAX(`create_time`)
    ;
    """
    )
    query_job.result()
    print(f"Youbike_ODS.bike_station has been created")

youbike_ods_combine_create()

In [ ]:
# sno                int64
# sna               object
# tot                int64
# sbi                int64
# sarea             object
# mday              object
# lat              float64
# lng              float64
# ar                object
# sareaen           object
# snaen             object
# aren              object
# bemp               int64
# act                int64
# srcUpdateTime     object
# updateTime        object
# infoTime          object
# infoDate          object

In [ ]:
def youbike_bqsrc_to_ods_station_name(client:bigquery.Client=BQ_CLIENT):
    query_job=client.query(
       """"
       CREATE OR REPLACE EXTERNAL TABLE `Youbike_ODS.bike_station` AS 
       SELECT
         CAST(`sno` AS INT) AS  `bike_station_id`,
         CAST(`sna` AS STRING) AS  `station_name`,
         CAST(`sarea` AS INT) AS  `total_space`,
         CAST(`sarea` AS STRING) AS  `district`,
         CAST(`sarea` AS FLOAT64) AS  `lat`,
         CAST(`sarea` AS FLOAT64) AS  `lng`,
         CAST(`sarea` AS STRING) AS  `address`,
         CAST(`sarea` AS INT) AS  `disable`
        FROM 'Youbike_ODS.youbike_src'
       
       """ 
    )

In [ ]:
# CREATE TABLE `bike_station` (
#   `bike_station_id` int PRIMARY KEY,
#   `station_name` varchar(100),
#   `total_space` int,
#   `lat` decimal(8,6),
#   `lng` decimal(9,6),
#   `city_code` char(3),
#   `district` varchar(20),
#   `address` varchar(100),
#   `disable` boolean,
#   `create_time` timestamp,
#   `update_time` timestamp
# );

In [22]:
def delete_dataset(dataset_name:str ,client: bigquery.Client = BQ_CLIENT):  #刪除dataset名稱
    porject_name = client.project
    dataset_id = f"{porject_name}.{dataset_name}"
    client.delete_dataset(dataset=dataset_id,delete_contents=True,not_found_ok=True)
    print(f"dataset {dataset_name} in project {porject_name} has been delete")
delete_dataset("Youbike_ODS")

dataset Youbike_ODS in project tir101-group2-422603 has been delete

In [7]:
def etl_sales_src_to_bq(client: bigquery.Client = BQ_CLIENT) -> None:
    query_job = client.query(
        """
        CREATE OR REPLACE EXTERNAL TABLE `bike_v1.youbike_ods_test1`
        WITH PARTITION COLUMNS
        OPTIONS (
        format = 'CSV',
        uris = ['gs://youbike_realtime/*.csv'],
        hive_partition_uri_prefix = 'gs://youbike_realtime/',
        skip_leading_rows = 1,
        max_bad_records = 1
        );
        """
    )

    query_job.result()

    print("youbike updated.")

In [5]:
etl_sales_src_to_bq()

youbike updated.

In [43]:
def query_stackoverflow(client: bigquery.Client = BQ_CLIENT):
    query_job = client.query(
        """
        SELECT *
        FROM `Youbike_ODS.youbike_src`
        LIMIT 3
        """
    )
    return query_job.to_dataframe()  # Convert result to DataFrame

df = query_stackoverflow()

In [67]:
df=pd.read_csv("dt=04_24_2024_01_50.csv")
df.dtypes

sno                int64
sna               object
tot                int64
sbi                int64
sarea             object
mday              object
lat              float64
lng              float64
ar                object
sareaen           object
snaen             object
aren              object
bemp               int64
act                int64
srcUpdateTime     object
updateTime        object
infoTime          object
infoDate          object
dtype: object

In [50]:
df = pd.read_csv("youbiketest.csv")
df.head(2)

,sno,sna,sarea,mday,ar,sareaen,snaen,aren,act,srcUpdateTime,updateTime,infoTime,infoDate,total,available_rent_bikes,latitude,longitude,available_return_bikes,dt
0,500101005,YouBike2.0_辛亥復興路口西北側,大安區,2024-05-06 07:58:18+00:00,復興南路二段368號,Daan Dist.,YouBike2.0_Xinhai Fuxing Rd. Intersection (Nor...,No. 368， Sec. 2， Fuxing S. Rd.,1,2024-05-06 07:58:26+00:00,2024-05-06 07:58:51+00:00,2024-05-06 07:58:18+00:00,2024-05-06,16,8,25.02153,121.54299,8,05_06_2024
1,500101006,YouBike2.0_復興南路二段280號前,大安區,2024-05-06 07:57:36+00:00,復興南路二段280號,Daan Dist.,YouBike2.0_No. 280， Sec. 2， Fuxing S. Rd.,No. 280， Sec. 2， Fuxing S. Rd.,1,2024-05-06 07:58:26+00:00,2024-05-06 07:58:51+00:00,2024-05-06 07:57:36+00:00,2024-05-06,11,1,25.02429,121.54328,10,05_06_2024

In [35]:
df.to_csv("youbiketest.csv",index=False,encoding="utf-8")

In [37]:
df

,sno,sna,sarea,mday,ar,sareaen,snaen,aren,act,srcUpdateTime,updateTime,infoTime,infoDate,total,available_rent_bikes,latitude,longitude,available_return_bikes,dt
0,500101005,YouBike2.0_辛亥復興路口西北側,大安區,2024-05-06 07:58:18+00:00,復興南路二段368號,Daan Dist.,YouBike2.0_Xinhai Fuxing Rd. Intersection (Nor...,No. 368， Sec. 2， Fuxing S. Rd.,1,2024-05-06 07:58:26+00:00,2024-05-06 07:58:51+00:00,2024-05-06 07:58:18+00:00,2024-05-06,16,8,25.021530,121.542990,8,05_06_2024
1,500101006,YouBike2.0_復興南路二段280號前,大安區,2024-05-06 07:57:36+00:00,復興南路二段280號,Daan Dist.,YouBike2.0_No. 280， Sec. 2， Fuxing S. Rd.,No. 280， Sec. 2， Fuxing S. Rd.,1,2024-05-06 07:58:26+00:00,2024-05-06 07:58:51+00:00,2024-05-06 07:57:36+00:00,2024-05-06,11,1,25.024290,121.543280,10,05_06_2024
2,500101009,YouBike2.0_新生南路三段66號前,大安區,2024-05-06 07:24:18+00:00,新生南路三段66號東側,Daan Dist.,YouBike2.0_No. 66， Sec. 3， Xinsheng S. Rd.,No. 66， Sec. 3， Xinsheng S. Rd. (East),1,2024-05-06 07:58:26+00:00,2024-05-06 07:58:51+00:00,2024-05-06 07:24:18+00:00,2024-05-06,16,1,25.019760,121.533840,15,05_06_2024
3,500101019,YouBike2.0_和平臥龍街口,大安區,2024-05-06 07:58:19+00:00,臥龍街1號,Daan Dist.,YouBike2.0_Heping Wolong St. Intersection,No. 1， Wolong St.,1,2024-05-06 07:58:26+00:00,2024-05-06 07:58:51+00:00,2024-05-06 07:58:19+00:00,2024-05-06,15,9,25.024461,121.546705,6,05_06_2024
4,500101034,YouBike2.0_臺大動物醫院前,大安區,2024-05-06 07:53:14+00:00,基隆路三段155巷/基隆路四段口,Daan Dist.,YouBike2.0_NTU Veterinary Hospital,Ln. 155， Sec. 3， Keelung Rd. Intersection,1,2024-05-06 07:58:26+00:00,2024-05-06 07:58:51+00:00,2024-05-06 07:53:14+00:00,2024-05-06,18,17,25.015760,121.542910,0,05_06_2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340932,500119071,YouBike2.0_臺大計資中心南側,臺大公館校區,2024-05-10 10:08:20+00:00,臺大計算機網路資訊中心南側,NTU Dist,YouBike2.0_NTU Computer and Information Networ...,NTU Computer and Information Networking Center...,1,2024-05-10 10:08:25+00:00,2024-05-10 10:08:51+00:00,2024-05-10 10:08:20+00:00,2024-05-10,34,15,25.020360,121.539920,4,05_10_2024
1340933,500119072,YouBike2.0_臺大原分所北側,臺大公館校區,2024-05-10 10:08:20+00:00,臺大原子與分子科學研究所東北側,NTU Dist,YouBike2.0_NTU Institute of Atomic and Molecul...,NTU Institute of Atomic and Molecular Sciences...,1,2024-05-10 10:08:25+00:00,2024-05-10 10:08:51+00:00,2024-05-10 10:08:20+00:00,2024-05-10,12,11,25.018810,121.538680,1,05_10_2024
1340934,500119075,YouBike2.0_臺大第一活動中心西南側,臺大公館校區,2024-05-10 10:07:19+00:00,第一學生活動中心東南側,NTU Dist,YouBike2.0_NTU 1st Student Activity Center(Sou...,NTU 1st Student Activity Center(Southeast),1,2024-05-10 10:08:25+00:00,2024-05-10 10:08:51+00:00,2024-05-10 10:07:19+00:00,2024-05-10,40,17,25.017610,121.539950,3,05_10_2024
1340935,500119081,YouBike2.0_臺大教研館北側,臺大公館校區,2024-05-10 10:07:19+00:00,臺大雅頌廣場東南側,NTU Dist,YouBike2.0_NTU Teaching and Research Building(...,NTU The Odeum Square(Southeast),1,2024-05-10 10:08:25+00:00,2024-05-10 10:08:51+00:00,2024-05-10 10:07:19+00:00,2024-05-10,11,5,25.013370,121.539090,6,05_10_2024
1340936,500119089,YouBike2.0_臺大獸醫館南側,臺大公館校區,2024-05-10 10:08:20+00:00,臺大獸醫系館南側,NTU Dist,YouBike2.0_NTU Dept. of Veterinary Medicine(So...,NTU Dept. of Veterinary Medicine(South),1,2024-05-10 10:08:25+00:00,2024-05-10 10:08:51+00:00,2024-05-10 10:08:20+00:00,2024-05-10,24,22,25.017910,121.542420,1,05_10_2024