In [41]:
# index_col=0 不要產生預設的index
import pandas as pd
path="/Users/laura/Desktop/TIR101_Group2/bike/bile_usage_realtime.csv"
df = pd.read_csv(path,index_col=0)

In [42]:
# CREATE TABLE `bike_station` (
#   `bike_station_id` int PRIMARY KEY,
#   `station_name` varchar(100),
#   `total_space` int,
#   `lat` decimal(8,6),
#   `lng` decimal(9,6),
#   `city_code` char(3),
#   `district` varchar(20),
#   `address` varchar(100),
#   `disable` boolean,
#   `create_time` timestamp,
#   `update_time` timestamp
# );

In [43]:
df.head()

,sno,sna,tot,sbi,sarea,mday,lat,lng,ar,sareaen,snaen,aren,bemp,act,srcUpdateTime,updateTime,infoTime,infoDate
0,500101001,YouBike2.0_捷運科技大樓站,28,1,大安區,2024-04-30 13:05:19,25.02605,121.54360,復興南路二段235號前,Daan Dist.,YouBike2.0_MRT Technology Bldg. Sta.,No.235， Sec. 2， Fuxing S. Rd.,27,1,2024-04-30 13:07:25,2024-04-30 13:07:51,2024-04-30 13:05:19,2024-04-30
1,500101002,YouBike2.0_復興南路二段273號前,21,1,大安區,2024-04-30 13:06:19,25.02565,121.54357,復興南路二段273號西側,Daan Dist.,YouBike2.0_No.273， Sec. 2， Fuxing S. Rd.,No.273， Sec. 2， Fuxing S. Rd. (West),20,1,2024-04-30 13:07:25,2024-04-30 13:07:51,2024-04-30 13:06:19,2024-04-30
2,500101003,YouBike2.0_國北教大實小東側門,16,6,大安區,2024-04-30 12:59:18,25.02429,121.54124,和平東路二段96巷7號,Daan Dist.,YouBike2.0_NTUE Experiment Elementary School (...,No. 7， Ln. 96， Sec. 2， Heping E. Rd,10,1,2024-04-30 13:07:25,2024-04-30 13:07:51,2024-04-30 12:59:18,2024-04-30
3,500101004,YouBike2.0_和平公園東側,11,1,大安區,2024-04-30 13:07:18,25.02351,121.54282,和平東路二段118巷33號,Daan Dist.,YouBike2.0_Heping Park (East),No. 33， Ln. 118， Sec. 2， Heping E. Rd,10,1,2024-04-30 13:07:25,2024-04-30 13:07:51,2024-04-30 13:07:18,2024-04-30
4,500101005,YouBike2.0_辛亥復興路口西北側,16,0,大安區,2024-04-30 13:07:13,25.02153,121.54299,復興南路二段368號,Daan Dist.,YouBike2.0_Xinhai Fuxing Rd. Intersection (Nor...,No. 368， Sec. 2， Fuxing S. Rd.,16,1,2024-04-30 13:07:25,2024-04-30 13:07:51,2024-04-30 13:07:13,2024-04-30

In [44]:
#刪除不要的欄位
df = df.drop(['sbi','mday','sareaen','snaen',
              'aren','srcUpdateTime','infoTime',
              'infoDate','bemp','updateTime'
              
              ],axis=1,errors='ignore')
df.head()

,sno,sna,tot,sarea,lat,lng,ar,act
0,500101001,YouBike2.0_捷運科技大樓站,28,大安區,25.02605,121.54360,復興南路二段235號前,1
1,500101002,YouBike2.0_復興南路二段273號前,21,大安區,25.02565,121.54357,復興南路二段273號西側,1
2,500101003,YouBike2.0_國北教大實小東側門,16,大安區,25.02429,121.54124,和平東路二段96巷7號,1
3,500101004,YouBike2.0_和平公園東側,11,大安區,25.02351,121.54282,和平東路二段118巷33號,1
4,500101005,YouBike2.0_辛亥復興路口西北側,16,大安區,25.02153,121.54299,復興南路二段368號,1

In [45]:
# 使用mapping 重新定義欄位新名稱
mapping = {'sno':'bike_station_id',
           'sna':'station_name',
           'tot':'total_space',
           'sarea':'district',
           'lat':'lat',
           'lng':'lng',
           'ar':'address',
           'act':'disable'
           }

In [46]:
# 將重新定義的新欄位名稱 套用到df 
# ,axis=1 ->指定‘欄’
df = df.rename(mapping,axis=1)

In [47]:
# 新增欄位'city_code'
# 將欄位'city_code' 給統一值'TPE'
df['city_code']='TPE'

In [48]:
df

,bike_station_id,station_name,total_space,district,lat,lng,address,disable,city_code
0,500101001,YouBike2.0_捷運科技大樓站,28,大安區,25.02605,121.54360,復興南路二段235號前,1,TPE
1,500101002,YouBike2.0_復興南路二段273號前,21,大安區,25.02565,121.54357,復興南路二段273號西側,1,TPE
2,500101003,YouBike2.0_國北教大實小東側門,16,大安區,25.02429,121.54124,和平東路二段96巷7號,1,TPE
3,500101004,YouBike2.0_和平公園東側,11,大安區,25.02351,121.54282,和平東路二段118巷33號,1,TPE
4,500101005,YouBike2.0_辛亥復興路口西北側,16,大安區,25.02153,121.54299,復興南路二段368號,1,TPE
...,...,...,...,...,...,...,...,...,...
1408,500119087,YouBike2.0_臺大總圖書館西南側,30,臺大公館校區,25.01690,121.54031,臺大圖書館西南側,1,TPE
1409,500119088,YouBike2.0_臺大黑森林西側,20,臺大公館校區,25.01995,121.54347,臺大霖澤館南側,1,TPE
1410,500119089,YouBike2.0_臺大獸醫館南側,24,臺大公館校區,25.01791,121.54242,臺大獸醫系館南側,1,TPE
1411,500119090,YouBike2.0_臺大新體育館東南側,40,臺大公館校區,25.02112,121.53591,臺大體育館東側,1,TPE
1412,500119091,YouBike2.0_臺大明達館北側(員工宿舍),18,臺大公館校區,25.01816,121.54469,明達館北側前空地,1,TPE

In [49]:
# 單獨確認->處理將'YouBike2.0_'移除
text = 'YouBike2.0_捷運科技大樓站'
prefix = 'YouBike2.0_'
result = text.replace(prefix, '')

In [50]:
# 處理將'YouBike2.0_'移除 ->定義為函式
def rename_station(text):
    prefix = 'YouBike2.0_'
    result = text.replace(prefix, '')
    return result

In [51]:
# 處理將'YouBike2.0_'移除的函式 套用到dataframe
df['station_name'] = df['station_name'].apply(rename_station)

In [52]:
df.head()

,bike_station_id,station_name,total_space,district,lat,lng,address,disable,city_code
0,500101001,捷運科技大樓站,28,大安區,25.02605,121.54360,復興南路二段235號前,1,TPE
1,500101002,復興南路二段273號前,21,大安區,25.02565,121.54357,復興南路二段273號西側,1,TPE
2,500101003,國北教大實小東側門,16,大安區,25.02429,121.54124,和平東路二段96巷7號,1,TPE
3,500101004,和平公園東側,11,大安區,25.02351,121.54282,和平東路二段118巷33號,1,TPE
4,500101005,辛亥復興路口西北側,16,大安區,25.02153,121.54299,復興南路二段368號,1,TPE

In [53]:
# dataframe 整理好-> 連結sql
from urllib.parse import quote_plus

import pandas as pd
from sqlalchemy import create_engine

username = quote_plus("root")
password = quote_plus("password")
server = "localhost:55000"
db_name = "group2_db"

conn = create_engine(
    f"mysql+pymysql://{username}:{password}@{server}/{db_name}",
).connect()

In [54]:
# 把dataframe insert to sql
df.to_sql('bike_station',conn,
          if_exists='append',index=False)

1413